-- MySQL Script generated by MySQL Workbench
-- Thu Mar 11 10:00:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EndangeredSpecies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EndangeredSpecies` (
  `EntityID` INT NOT NULL,
  `SpeciesName` VARCHAR(100) NOT NULL,
  `Endangered(Y/N)` TINYINT NOT NULL,
  `EndangeredStatus` VARCHAR(45) NOT NULL,
  `WhereEndangered` VARCHAR(200) NOT NULL,
  `HabitatType` VARCHAR(45) NOT NULL,
  `PreservedAcreage` VARCHAR(45) NOT NULL,
  `Genus (ScientificName)` VARCHAR(150) NOT NULL,
  `Species Type` VARCHAR(100) NOT NULL,
  `ReadMore` VARCHAR(300) NULL,
  `FurtherReading` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`EntityID`),
  UNIQUE INDEX `EntityID_UNIQUE` (`EntityID` ASC) VISIBLE,
  UNIQUE INDEX `SpeciesName_UNIQUE` (`SpeciesName` ASC) VISIBLE,
  UNIQUE INDEX `ReadMore_UNIQUE` (`ReadMore` ASC) VISIBLE,
  UNIQUE INDEX `Genus (ScientificName)_UNIQUE` (`Genus (ScientificName)` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
